version: 2.1

jobs:
  create_infrastructure: 
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --
              --region us-east-1
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c9:1b:48:e1:58:06:47:cc:ae:18:f2:7f:cb:a3:87:2a"
      - run:
          name: Install Ansible
          command: |
            # Install Ansible
            apt-get update -y
            apt install ansible -y
            which ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            cat  inventory.txt
            ansible-playbook -i  inventory.txt  main.yml
  # build:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - run: npm i
  #     - save_cache:
  #         paths:
  #           - "/src/node_modules"
  #         key: "npm-packages"
  #     - run: npm run lint
  # test:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys: 
  #           - "npm-packages"
  #     - run: npm i
  #     - run: npm run test
  # analyze:
    # docker:
    #   - image: circleci/node:13.8.0
    # steps:
    #   - checkout

workflows:
  my_worflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure
      # - build
      # - test:
      #     requires:
      #       -  build
      # - analyze:
      #     requires:
      #       - test